name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    services:
      postgres:
        image: postgres:16.3-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        env:
          MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
          MAIN_DATASOURCE_USERNAME: postgres
          MAIN_DATASOURCE_PASSWORD: postgres
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Build Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./gradlew -Pvaadin.productionMode=true bootBuildImage
